version: "3.9"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - dbdata:/data/db
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: admin
    #   MONGO_INITDB_DATABASE: pokerstats
    networks:
      - backend
  express:
    image: mongo-express
    restart: always
    container_name: express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - backend
    depends_on:
      - mongodb
     

  nodejs:
    build: .
    container_name: nodejs
    networks:
      - frontend
      - backend
    depends_on:
      - mongodb

  proxy:
    image: nginx
    restart: always
    container_name: proxy
    volumes:
      - ../proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../proxy/ssl/localhost.crt:/etc/ssl/certs/localhost.crt
      - ../proxy/ssl/localhost.key:/etc/ssl/private/localhost.key
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
    depends_on:
      - nodejs
      - express



networks:
  frontend:
  backend:
    driver: bridge
    
volumes:
  dbdata:
